// <auto-generated />
using System;
using LeoClinic.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeoClinic.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811063615_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeoClinic.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailabilityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId")
                        .IsUnique()
                        .HasFilter("[Status] <> 3 AND [Status] <> 4");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailabilityId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 8,
                            Notes = "Annual checkup",
                            PatientId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AvailabilityId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 9,
                            Notes = "Chest pain consultation",
                            PatientId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AvailabilityId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 10,
                            Notes = "Skin rash examination",
                            PatientId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            AvailabilityId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 11,
                            Notes = "Child vaccination",
                            PatientId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AvailabilityId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 12,
                            Notes = "Knee pain assessment",
                            PatientId = 5,
                            Status = 1
                        });
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LocationId");

                    b.ToTable("Availabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 8,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            IsBooked = true,
                            LocationId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 9,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            IsBooked = true,
                            LocationId = 2,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 10,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsBooked = true,
                            LocationId = 3,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 11,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            IsBooked = true,
                            LocationId = 4,
                            StartTime = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 12,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            IsBooked = true,
                            LocationId = 5,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.DoctorLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LocationId");

                    b.ToTable("DoctorLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 8,
                            LocationId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 9,
                            LocationId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 10,
                            LocationId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 11,
                            LocationId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 12,
                            LocationId = 5
                        });
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.DoctorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DoctorProfiles");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Bio = "Experienced general practitioner with 10 years of practice",
                            ContactNumber = "01012345678",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            Price = 200m,
                            SpecialityId = 1,
                            UserId = 9
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Cardiologist specialized in interventional cardiology",
                            ContactNumber = "01123456789",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            Price = 500m,
                            SpecialityId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Dermatologist with expertise in cosmetic dermatology",
                            ContactNumber = "01234567890",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            Price = 350m,
                            SpecialityId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 11,
                            Bio = "Pediatrician caring for children from birth to adolescence",
                            ContactNumber = "01098765432",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            Price = 250m,
                            SpecialityId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 12,
                            Bio = "Orthopedic surgeon specializing in sports injuries",
                            ContactNumber = "01187654321",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApproved = true,
                            Price = 400m,
                            SpecialityId = 5,
                            UserId = 13
                        });
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "15 Tahrir Street",
                            City = "Cairo",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Main Clinic",
                            Phone = "02-27951234"
                        },
                        new
                        {
                            Id = 2,
                            Address = "22 El Corniche Road",
                            City = "Alexandria",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Branch Clinic",
                            Phone = "03-34856789"
                        },
                        new
                        {
                            Id = 3,
                            Address = "8 Pyramids Street",
                            City = "Giza",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hospital Center",
                            Phone = "02-37891234"
                        },
                        new
                        {
                            Id = 4,
                            Address = "10 El Gomhouria Street",
                            City = "Mansoura",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Medical Center",
                            Phone = "050-2345678"
                        },
                        new
                        {
                            Id = 5,
                            Address = "5 El Saada Street",
                            City = "Tanta",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Health Center",
                            Phone = "040-3456789"
                        });
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Your appointment has been confirmed",
                            RetryCount = 0,
                            SentAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Type = 0,
                            UserId = 14
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Your appointment has been confirmed",
                            RetryCount = 0,
                            SentAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Type = 0,
                            UserId = 15
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Your appointment has been confirmed",
                            RetryCount = 0,
                            SentAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Type = 1,
                            UserId = 16
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Your appointment has been confirmed",
                            RetryCount = 0,
                            SentAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Type = 2,
                            UserId = 17
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Your appointment has been confirmed",
                            RetryCount = 0,
                            SentAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Type = 0,
                            UserId = 18
                        });
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.PatientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PatientProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "23 Mohamed Ali Street, Cairo",
                            ContactNumber = "01011112222",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = true,
                            UserId = 14
                        },
                        new
                        {
                            Id = 2,
                            Address = "10 Sheraton Street, Cairo",
                            ContactNumber = "01122223333",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = true,
                            UserId = 15
                        },
                        new
                        {
                            Id = 3,
                            Address = "5 La Mansión Street, Alexandria",
                            ContactNumber = "01233334444",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1995, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = true,
                            UserId = 16
                        },
                        new
                        {
                            Id = 4,
                            Address = "18 El-Thawra Street, Giza",
                            ContactNumber = "01044445555",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = true,
                            UserId = 17
                        },
                        new
                        {
                            Id = 5,
                            Address = "7 El-Nasr Street, Mansoura",
                            ContactNumber = "01155556666",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1988, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = true,
                            UserId = 18
                        });
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 200m,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientId = 1,
                            PaymentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Cash",
                            Status = 1,
                            TransactionReference = "TXN-001"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 500m,
                            AppointmentId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientId = 2,
                            PaymentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Credit Card",
                            Status = 1,
                            TransactionReference = "TXN-002"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 350m,
                            AppointmentId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientId = 3,
                            PaymentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Vodafone Cash",
                            Status = 1,
                            TransactionReference = "TXN-003"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 250m,
                            AppointmentId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientId = 4,
                            PaymentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "InstaPay",
                            Status = 1,
                            TransactionReference = "TXN-004"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 400m,
                            AppointmentId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientId = 5,
                            PaymentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Cash",
                            Status = 1,
                            TransactionReference = "TXN-005"
                        });
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            PatientId = 1,
                            Rate = 5,
                            Review = "Very professional and thorough examination"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            PatientId = 2,
                            Rate = 4,
                            Review = "Excellent cardiologist, highly recommended"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            PatientId = 3,
                            Rate = 5,
                            Review = "Best dermatologist I have ever visited"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            PatientId = 4,
                            Rate = 4,
                            Review = "Very gentle with children, my kid loved her"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            PatientId = 5,
                            Rate = 5,
                            Review = "Solved my knee problem completely"
                        });
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "General medical practice",
                            Name = "General Practice"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Heart and cardiovascular system",
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Skin, hair, and nails",
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Children's health",
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bones, joints, and muscles",
                            Name = "Orthopedics"
                        });
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmed.ali@clinic.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmed",
                            IsBlocked = false,
                            LastName = "Ali",
                            PasswordHash = "$2a$11$wygh8/MdNtSSImU9VL2KsORPOKi9c6Imk4MAG6EzKD9PhZ8QPMMsu",
                            Role = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mohamed.salem@clinic.com",
                            EmailConfirmed = true,
                            FirstName = "Mohamed",
                            IsBlocked = false,
                            LastName = "Salem",
                            PasswordHash = "$2a$11$wygh8/MdNtSSImU9VL2KsORPOKi9c6Imk4MAG6EzKD9PhZ8QPMMsu",
                            Role = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara.khaled@clinic.com",
                            EmailConfirmed = true,
                            FirstName = "Sara",
                            IsBlocked = false,
                            LastName = "Khaled",
                            PasswordHash = "$2a$11$wygh8/MdNtSSImU9VL2KsORPOKi9c6Imk4MAG6EzKD9PhZ8QPMMsu",
                            Role = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fatma.hassan@clinic.com",
                            EmailConfirmed = true,
                            FirstName = "Fatma",
                            IsBlocked = false,
                            LastName = "Hassan",
                            PasswordHash = "$2a$11$wygh8/MdNtSSImU9VL2KsORPOKi9c6Imk4MAG6EzKD9PhZ8QPMMsu",
                            Role = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "omar.youssef@clinic.com",
                            EmailConfirmed = true,
                            FirstName = "Omar",
                            IsBlocked = false,
                            LastName = "Youssef",
                            PasswordHash = "$2a$11$wygh8/MdNtSSImU9VL2KsORPOKi9c6Imk4MAG6EzKD9PhZ8QPMMsu",
                            Role = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ali.mahmoud@clinic.com",
                            EmailConfirmed = true,
                            FirstName = "Ali",
                            IsBlocked = false,
                            LastName = "Mahmoud",
                            PasswordHash = "$2a$11$wygh8/MdNtSSImU9VL2KsORPOKi9c6Imk4MAG6EzKD9PhZ8QPMMsu",
                            Role = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hassan.ibrahim@clinic.com",
                            EmailConfirmed = true,
                            FirstName = "Hassan",
                            IsBlocked = false,
                            LastName = "Ibrahim",
                            PasswordHash = "$2a$11$wygh8/MdNtSSImU9VL2KsORPOKi9c6Imk4MAG6EzKD9PhZ8QPMMsu",
                            Role = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nour.abdelrahman@clinic.com",
                            EmailConfirmed = true,
                            FirstName = "Nour",
                            IsBlocked = false,
                            LastName = "Abdelrahman",
                            PasswordHash = "$2a$11$wygh8/MdNtSSImU9VL2KsORPOKi9c6Imk4MAG6EzKD9PhZ8QPMMsu",
                            Role = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "layla.mostafa@clinic.com",
                            EmailConfirmed = true,
                            FirstName = "Layla",
                            IsBlocked = false,
                            LastName = "Mostafa",
                            PasswordHash = "$2a$11$wygh8/MdNtSSImU9VL2KsORPOKi9c6Imk4MAG6EzKD9PhZ8QPMMsu",
                            Role = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "youssef.adel@clinic.com",
                            EmailConfirmed = true,
                            FirstName = "Youssef",
                            IsBlocked = false,
                            LastName = "Adel",
                            PasswordHash = "$2a$11$wygh8/MdNtSSImU9VL2KsORPOKi9c6Imk4MAG6EzKD9PhZ8QPMMsu",
                            Role = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin.seed@clinic.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            IsBlocked = false,
                            LastName = "User",
                            PasswordHash = "$2a$11$wygh8/MdNtSSImU9VL2KsORPOKi9c6Imk4MAG6EzKD9PhZ8QPMMsu",
                            Role = 0
                        });
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.VerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VerificationCodes");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("LeoClinic.Domain.Entities.Availability", "Availability")
                        .WithMany("Appointments")
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeoClinic.Domain.Entities.DoctorProfile", "DoctorProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeoClinic.Domain.Entities.PatientProfile", "PatientProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Availability");

                    b.Navigation("DoctorProfile");

                    b.Navigation("PatientProfile");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Availability", b =>
                {
                    b.HasOne("LeoClinic.Domain.Entities.DoctorProfile", "DoctorProfile")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeoClinic.Domain.Entities.Location", "Location")
                        .WithMany("Availabilities")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorProfile");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.DoctorLocation", b =>
                {
                    b.HasOne("LeoClinic.Domain.Entities.DoctorProfile", "DoctorProfile")
                        .WithMany("DoctorLocations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeoClinic.Domain.Entities.Location", "Location")
                        .WithMany("DoctorLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorProfile");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.DoctorProfile", b =>
                {
                    b.HasOne("LeoClinic.Domain.Entities.Speciality", "Speciality")
                        .WithMany("DoctorProfiles")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeoClinic.Domain.Entities.User", "User")
                        .WithOne("DoctorProfile")
                        .HasForeignKey("LeoClinic.Domain.Entities.DoctorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Speciality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Notification", b =>
                {
                    b.HasOne("LeoClinic.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Notifications")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LeoClinic.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.PatientProfile", b =>
                {
                    b.HasOne("LeoClinic.Domain.Entities.User", "User")
                        .WithOne("PatientProfile")
                        .HasForeignKey("LeoClinic.Domain.Entities.PatientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Payment", b =>
                {
                    b.HasOne("LeoClinic.Domain.Entities.Appointment", "Appointment")
                        .WithOne("Payment")
                        .HasForeignKey("LeoClinic.Domain.Entities.Payment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeoClinic.Domain.Entities.PatientProfile", "PatientProfile")
                        .WithMany("Payments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("PatientProfile");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Rating", b =>
                {
                    b.HasOne("LeoClinic.Domain.Entities.DoctorProfile", "DoctorProfile")
                        .WithMany("Ratings")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeoClinic.Domain.Entities.PatientProfile", "PatientProfile")
                        .WithMany("Ratings")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoctorProfile");

                    b.Navigation("PatientProfile");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("LeoClinic.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.VerificationCode", b =>
                {
                    b.HasOne("LeoClinic.Domain.Entities.User", "User")
                        .WithMany("VerificationCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Availability", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.DoctorProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");

                    b.Navigation("DoctorLocations");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Location", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("DoctorLocations");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.PatientProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Payments");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.Speciality", b =>
                {
                    b.Navigation("DoctorProfiles");
                });

            modelBuilder.Entity("LeoClinic.Domain.Entities.User", b =>
                {
                    b.Navigation("DoctorProfile");

                    b.Navigation("Notifications");

                    b.Navigation("PatientProfile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("VerificationCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
